import Navbar from '@/components/layouts/Navbar'
import '../globals.css'
import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'
import Image from "next/image"
import Footer from '@/components/layouts/Navbar/Footer'
import { Toaster } from '@/components/ui/toaster'
import AuthProvider from '@/providers/AuthProvider'

const epilogue = Epilogue({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${epilogue.className} relative overflow-x-hidden`}>
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  )
}
